In [1]:
import torch

In [15]:
inputmask = torch.tensor([[1]*3], dtype=torch.int)

In [18]:
inputmask.unsqueeze(2)

tensor([[[1],
         [1],
         [1]]], dtype=torch.int32)

In [11]:
th = torch.tensor([[[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3],[1,2,3]]], dtype=torch.float)

In [24]:
m = torch.tensor([[1,1,0], [1,0,0]], dtype=torch.int)
tm = torch.tril(torch.ones(3, 3))

In [25]:
m.unsqueeze(1).shape

torch.Size([2, 1, 3])

In [28]:
m.unsqueeze(2)

tensor([[[1],
         [1],
         [0]],

        [[1],
         [0],
         [0]]], dtype=torch.int32)

In [34]:
min = torch.stack([[torch.tensor([1,1,0], dtype=torch.int),torch.tensor([1,0,0], dtype=torch.int),torch.tensor([1,1,1],dtype=torch.int)][i] for i in range(2)])

In [36]:
min.unsqueeze(2)

tensor([[[1],
         [1],
         [0]],

        [[1],
         [0],
         [0]]], dtype=torch.int32)

In [37]:
#wei = th.masked_fill(tm==0, float("-inf"))
wei = th.masked_fill(min.unsqueeze(2) == 0, 0)

In [38]:
wei

tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [0., 0., 0.]],

        [[1., 2., 3.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [3]:
on = True
while on:
    q=input()

    print(q)
    if q == "quit":
        on = False

d
d
quit


In [16]:
class cl(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.tab = torch.nn.Embedding(3, 32)

    def forward(self, x):
        x = self.tab(x)
        return x

In [23]:
emb = torch.tensor([[32],[32],[32]],dtype=torch.int)
model = cl()
a, T = emb.shape

In [24]:
model(torch.arange(T))

tensor([[-0.5741,  0.3800, -1.3000,  0.4301,  1.1825, -1.8453,  0.6297,  0.8339,
          1.2079, -1.1570, -0.0930,  0.0070,  0.8128,  0.8856,  0.4237, -1.3723,
          0.5453, -0.6681, -1.3226,  1.7194,  0.0357,  0.4929, -0.8637, -0.9682,
          2.7969, -1.1800,  0.6577, -2.5229,  0.4473,  0.3468, -0.6053, -0.2795]],
       grad_fn=<EmbeddingBackward0>)

In [1]:
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.trainers import WordLevelTrainer
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.normalizers import Lowercase

In [2]:
src_tokenizer = Tokenizer(WordLevel(unk_token="[UNK]"))
src_tokenizer.pre_tokenizer = Whitespace()
src_tokenizer.normalizer = Lowercase()
trainer = WordLevelTrainer(special_tokens=["[UNK]", "[SOS]", "[EOS]", "[PAD]"], min_frequency=2)
src_tokenizer.train(["D:/robo_data/train.source"], trainer=trainer)
src_vocab_size = src_tokenizer.get_vocab_size()

In [3]:
s = src_tokenizer.encode("[SOS] " + "was ist das dog").ids
print(s)
s2 = src_tokenizer.encode("[SOS] " + "WAs\nIst DAS dog").ids
print(s2)

[1, 43, 3307, 2745, 4342]
[1, 43, 3307, 2745, 4342]


In [14]:
src_tokenizer.decode(s2)

'was ist das dog'

In [21]:
"<PAD> ".lower() + "WAs Ist, DAS dog.".lower()

'<pad> was ist, das dog.'

In [20]:
th2 = th.view(18)

In [37]:
th2 = torch.tensor([[1.2,2.2,3.5,4.3,5.1,10.5]], dtype=torch.float)

In [42]:
torch.multinomial(th2, num_samples=1)

tensor([[4]])